import type { APIRoute } from 'astro';

// This endpoint returns a URL to the printable CV page. PDF should be generated by the hosting platform (e.g., Vercel functions with headless Chrome)
// or by a one-off script. For now, we provide a prerenderable HTML that mirrors the CV layout.

export const GET: APIRoute = async ({ url }) => {
  const locale = url.searchParams.get('locale') || 'pl';
  const target = `/cv/${locale}`;
  return new Response(null, { status: 302, headers: { Location: target } });
};


